"""
Movements API Routes — Movement tracking, timeline, and activity endpoints.

Provides RESTful access to the detection_events table with movement-focused
query patterns including person timelines, camera activity, and aggregations.
"""

from fastapi import APIRouter, Depends, Query, HTTPException
from typing import Optional

from app.models.movement import (
    MovementCreate,
    MovementResponse,
    MovementSummary,
)
from app.services.movement_service import MovementService
from app.core.security import get_current_user

router = APIRouter(prefix="/api/movements", tags=["Movements"])


@router.get("")
async def list_movements(
    person_id: Optional[str] = Query(None, description="Filter by person ID"),
    camera_id: Optional[str] = Query(None, description="Filter by camera ID"),
    event_type: Optional[str] = Query(
        None, description="Filter by event type: entry/exit/detection/unknown"
    ),
    start_date: Optional[str] = Query(
        None, description="Start date filter (ISO 8601)"
    ),
    end_date: Optional[str] = Query(
        None, description="End date filter (ISO 8601)"
    ),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    current_user: dict = Depends(get_current_user),
):
    """
    List movement events with filtering.

    Supports filtering by person, camera, event type, and date range.
    Ordered by most recent first.
    """
    return MovementService.list_movements(
        person_id=person_id,
        camera_id=camera_id,
        event_type=event_type,
        start_date=start_date,
        end_date=end_date,
        limit=limit,
        offset=offset,
    )


@router.get("/summary")
async def get_movement_summary(
    person_id: Optional[str] = Query(None, description="Filter by person"),
    camera_id: Optional[str] = Query(None, description="Filter by camera"),
    days: int = Query(7, ge=1, le=365, description="Days to look back"),
    current_user: dict = Depends(get_current_user),
):
    """
    Get aggregated movement summary with counts and averages.

    Provides total events, entries, exits, unknown count,
    unique persons, and average confidence over the specified period.
    """
    return MovementService.get_movement_summary(
        person_id=person_id,
        camera_id=camera_id,
        days=days,
    )


@router.get("/person/{person_id}/timeline")
async def get_person_timeline(
    person_id: str,
    days: int = Query(7, ge=1, le=90, description="Days to look back"),
    limit: int = Query(100, ge=1, le=500),
    current_user: dict = Depends(get_current_user),
):
    """
    Get chronological movement timeline for a specific person.

    Returns a list of all detection events for the person,
    sorted by most recent first.
    """
    timeline = MovementService.get_person_timeline(
        person_id=person_id,
        days=days,
        limit=limit,
    )
    return {
        "person_id": person_id,
        "timeline": timeline,
        "count": len(timeline),
    }


@router.get("/camera/{camera_id}/activity")
async def get_camera_activity(
    camera_id: str,
    hours: int = Query(24, ge=1, le=168, description="Hours to look back"),
    current_user: dict = Depends(get_current_user),
):
    """
    Get movement activity breakdown for a specific camera.

    Returns hourly event counts and recent events for the specified period.
    """
    return MovementService.get_camera_activity(
        camera_id=camera_id,
        hours=hours,
    )


@router.get("/{movement_id}")
async def get_movement(
    movement_id: str,
    current_user: dict = Depends(get_current_user),
):
    """Get details for a specific movement event."""
    return MovementService.get_movement(movement_id)


@router.post("", response_model=MovementResponse)
async def create_movement(
    data: MovementCreate,
    current_user: dict = Depends(get_current_user),
):
    """
    Manually record a movement event.

    Normally events are auto-generated by the vision pipeline,
    but this endpoint allows manual event injection for testing
    or external integrations.
    """
    return MovementService.create_movement(data.model_dump())


@router.delete("/cleanup")
async def cleanup_old_movements(
    days: int = Query(90, ge=30, le=365, description="Delete events older than N days"),
    current_user: dict = Depends(get_current_user),
):
    """
    Delete movement events older than the specified number of days.

    Requires admin access. Used for data retention management.
    """
    if current_user.get("role") not in ("admin", "superadmin"):
        raise HTTPException(status_code=403, detail="Admin access required")

    deleted = MovementService.delete_old_movements(days=days)
    return {
        "message": f"Deleted {deleted} movement events older than {days} days",
        "deleted_count": deleted,
    }
